use_frameworks!

platform :ios, '9.0'

target 'A_Example' do
  pod 'A', :path => '../'
  pod 'B_Category', :path => '../../B_Category'

  target 'A_Tests' do
    inherit! :search_paths

    
  end
end
